theme: jekyll-theme-cayman
title: Can I Pour into It? Robot Imagining Open Containability Affordance of Unknown Object via Physical Simulations
description: Hongtao Wu<sup>1</sup>, Gregory S. Chirikjian<sup>1, 2</sup>
description: <sup>1</sup> Laboratory for Computational Sensing Robotics (LCSR), Johns Hopkins University
description: <sup>2</sup> Department of Mechanical Engineering, National University of Singapore
